version: '3'
services:
  connector-trend-micro:
    image: pietrovitagliano/trend_micro:1.513
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_TRENDMICRO_ID}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=TrendMicro
      - CONNECTOR_SCOPE=attack-pattern,intrusion-set,malware,report,attack-info # MIME type or Stix Object
      - CONNECTOR_CONFIDENCE_LEVEL=100 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - TRENDMICRO_URL=https://newsroom.trendmicro.com/cyberthreat?pagetemplate=rss
      - TRENDMICRO_TIME_INTERVAL=7 # In days, must be strictly greater than 1
    restart: always
    depends_on:
      - opencti