opencti:
  url: 'http://opencti:8080'
  token: '2cf0a4fe-4ded-4931-901b-20e599b7f013'

connector:
  id: '5c57a122-5d9c-11ec-bf63-0242ac130002'
  type: 'INTERNAL_ENRICHMENT'
  name: 'Anyrun'
  scope: 'malware' # MIME type or SCO
  #connector_auto: 'true'
  confidence_level: 100 # From 0 (Unknown) to 100 (Fully trusted)
  log_level: 'info'